name: Artemis Build

on:
  push:
    branches: [ Development ]
    
env:
    AZURE_WEBAPP_PACKAGE_PATH: '.'      # set this to the path to your web app project, defaults to the repository root

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # Checkout the repo
    - uses: actions/checkout@v2
    
    # Setup .NET Core SDK
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100
        
    # Run dotnet build and publish
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Publish
      run: dotnet publish -c Release -o '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/artemis'
      
    # Run Tests
    - name: Test
      run: dotnet test --no-restore --verbosity normal
